### ISSUE TITLE
Include 'Pages' Section in Instant Search Result Page

### ISSUE THREAD

**Issue by Cmac2712** [algolia/algoliasearch-magento#1012]
Hi, 

Is it possible to include a 'Pages' section in the Instant Search Results Page, similar to how pages appear in the Autocomplete dropdown, or is there a way to include pages in the search results alongside products?

I couldn't find a straightforward way of doing this from the Instant search page customization docs.

Thanks, 

Craig

**Comment by JanPetr** [comment]
Hello @Cmac2712,

no, it's not possible today.
How would you like to the display pages on search results page?

**Comment by Cmac2712** [comment]
Hi Jan, 

I just need pages to appear on the results page, similar to how the categories section appears.

**Comment by JanPetr** [comment]
But `Categories` appear there as a filter and you can refine products by categories.

Pages cannot be used as a filter, so I'm not sure how to add it so it's not confusing for the customer. When it's added in the same way as categories and user clicks on it, he'd be redirected to the page instead of refining.

Do I miss something?
