### ISSUE TITLE
Magento magento_default_pages_tmp objectID(10) too big?

### ISSUE THREAD

**Issue by BigBlack** [algolia/algoliasearch-magento#1021]
I'm trying to use Algolia in Magento for autocomplete search. It tell me that this object is too big.. Now I'm not interested to algolia working or not. My interest is to understand what is this object. Where I can find it? What is it?

**Comment by damcou** [comment]
Hi @BigBlack !
If you get this error during the pages indexing, it must be referring to the CMS Page with 10 as ID (you can see it in your back-office with an URL such as this one if you didn't make any customization  : admin/cms_page/edit/page_id/10/ ) 

It is probably the content of the page which it too big to be indexed.

Hope this will help.

**Comment by mitcht** [comment]
It means the data being sent to Algolia is too large. For me, it was because i had every currency selected, and it was breaking the product sync. Try using something like PHPStorm + Xdebug and step through the code and just explore your objects being sent in lib/AlgoliaSearch/Client.php for to the request function.  You'll probably find quickly what is causing the object to be big.  There is a pretty small byte limit and we all know magento objects aren't exactly small.

**Comment by damcou** [comment]
Hi @BigBlack , I don't know if you have still the issue. I'll close this ticket but feel free to create a topic on our [discourse forum](https://discourse.algolia.com/tags/magento) if you're still experiencing it.
