### ISSUE TITLE
keyboard nagivation vs URL issue on autocomplete

### ISSUE THREAD

**Issue by alexgran** [algolia/algoliasearch-magento#1039]
We are using a heavily customized Algolia M1 on [https://www.bobbie.de](https://www.boobie.de).
One of the - rather trivial - modifications is that we don't store the whole path (including domain) in the index, but just add that in the template like so:

    
    <script type="text/template" id="autocomplete_products_template">
        <a class="algoliasearch-autocomplete-hit" href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>{{url}}">

Plus an observer code in indexing that strips the baseURL before the product goes to the index.

This is all working just fine.
When clicking on an autocomplete hit, this works as expected.
When the user is currently in a "folder", and uses the mouse to operate the autocomplete, some magic happens that messes up the final path.
So see that, go to, e.g. [https://www.bobbie.de/garten-und-landschaftsbau/flachenbelage/unterkonstruktionen/volfi-fugenkreuz-kunststoff-schwarz-17.html](https://www.bobbie.de/garten-und-landschaftsbau/flachenbelage/unterkonstruktionen/volfi-fugenkreuz-kunststoff-schwarz-17.html) and search for anything using autocomplete (might be the same product, so search for "kunst"). If you click the result - all fine.
If you use key-down + enter, you end up in https://www.bobbie.de/garten-und-landschaftsbau/flachenbelage/unterkonstruktionen/garten-und-landschaftsbau/flachenbelage/unterkonstruktionen/m-kn-kunststoffnagel-318.html - which gives a 404.

Any idea how to fix that?

**Comment by JanPetr** [comment]
Hello @alexgran!

The issue is that redirect after "Enter" is done via `autocomplete:selected` event of autocomplete menu: https://github.com/algolia/algoliasearch-magento/blob/master/js/algoliasearch/autocomplete.js#L108

This uses URL from record and redirects to it. As the URL in your record doesn't start with `/` or domain, the record's URL is appended to the end of current URL.
<img width="764" alt="screenshot 2018-06-27 06 00 35" src="https://user-images.githubusercontent.com/1058144/41952367-c96dfa5e-79cf-11e8-804d-de14ca1fb26f.png">

Solution would be either to:
- index a URL starting with `/` if all pages where the search is are on the same domain
- change the logic in JS code too to have domain in event (should be OK to override [`transformHit` method](https://github.com/algolia/algoliasearch-magento/blob/master/js/algoliasearch/internals/frontend/common.js#L57))

Can I ask you what's your motivation for not indexing domain in Algolia?

**Comment by alexgran** [comment]
Hi @JanPetr 
thanks for the quick feedback and pointing to the code. Didn't get that selected means enter pressed ;)
solution one is very straight forward I guess.
Motivation is twofold. first, we save a few bytes in record data (much more for images, where we also strip the static prefix). Second, we can use the same index accros domains. This is very usefull for testing/debugging etc.
regards
Alex

**Comment by alexgran** [comment]
Alright, modified my observer to make sure we always have a / in front of the URL, works fine.

**Comment by JanPetr** [comment]
Perfect, makes sense. Thanks for letting me know 👍
