### ISSUE TITLE
Wrong group price for configurable bundle products

### ISSUE THREAD

**Issue by michaelzangerle** [algolia/algoliasearch-magento#1116]
**Do you want to request a *feature* or report a *bug*?**
Bug

**Bug: What is the current behavior?**
When I have a bundle product with configuration options (e.g. a helmet and goggles combined) the special price is used as group price although the defined group price is less than the special price. If no special price is defined the normal price is indexed and displayed instead of the group price.

More details to the product: The helmet has to be configured because the customer needs to select a size. For a goggle the customer can choose between a few different ones which also have a different price. So there is a price range e.g. from € 127.00 to € 151.00. The group price is defined as 10% discount.

**Bug: What is the expected behavior?**
The group price should be used instead of the special price or normal price.

**Bug: What is the proposed solution?**
    - 

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**
Magento 1.9.3
Algolia 1.15.0

**Comment by damcou** [comment]
Hello there, I'm closing the issue as we didn't hear from you for a while.

Regarding the issue raised previously, it is still in our backlog and will be addressed as soon as possible.

In the meantime, you can keep track of it looking at our [M1 community board](https://github.com/algolia/algoliasearch-magento/projects/3).

If you are still experiencing further issues, please reach out to us at support@algolia.com with any error logs, screenshots of examples you can provide, as well as your APPID so that we can further assist you. Thanks!
