### ISSUE TITLE
active category removed from index

### ISSUE THREAD

**Issue by etessari** [algolia/algoliasearch-magento#1135]
**Do you want to request a *feature* or report a *bug*?**
Bug

**Bug: What is the current behavior?**
- login to admin
- navigate to catalog > categories
- change scope to a store level
- select category with property is_active
![admin-is-active](https://user-images.githubusercontent.com/10881108/59281881-501bd700-8c68-11e9-9060-a0f4c4054f08.jpg)
- save category
- added to algolia queue "removeCategories" action for the saved category

**Bug: What is the expected behavior?**
- added to algolia queue "rebuildCategoryIndex" action for the saved category

**Comment by damcou** [comment]
Hello there, I'm closing the issue as we didn't hear from you for a while.

Regarding the issue raised previously, it is still in our backlog and will be addressed as soon as possible.

In the meantime, you can keep track of it looking at our [M1 community board](https://github.com/algolia/algoliasearch-magento/projects/3).

If you are still experiencing further issues, please reach out to us at support@algolia.com with any error logs, screenshots of examples you can provide, as well as your APPID so that we can further assist you. Thanks!
