### ISSUE TITLE
Press Enter key on search input field redirects to product details page

### ISSUE THREAD

**Issue by faisal2010** [algolia/algoliasearch-magento#1139]
This issue is also in Algolia's magento demo site: https://magento.algolia.com/

## Current behavior
when press enter key after writing a search keyword in search input field if my mouse cursor is 
 currently at on any item in instant search result dialog it redirects to that item's details page instead of magento's search results page.

## Expected behavior
when press enter key after writing a search keyword in search input field it should redirects to search results page regardless of my mouse is currently on any item inside the instant search result dialog or not.

**Comment by damcou** [comment]
Hello there, I'm closing the issue as we didn't hear from you for a while.

Regarding the issue raised previously, it is still in our backlog and will be addressed as soon as possible.

In the meantime, you can keep track of it looking at our [M1 community board](https://github.com/algolia/algoliasearch-magento/projects/3).

If you are still experiencing further issues, please reach out to us at support@algolia.com with any error logs, screenshots of examples you can provide, as well as your APPID so that we can further assist you. Thanks!
