### ISSUE TITLE
Click analytics logic should not always apply for extra autocomplete sources

### ISSUE THREAD

**Issue by maxiloc** [algolia/algoliasearch-magento#1158]
When you have extra suggestion sources, that do not have clickAnalytics. For example hardcoded suggestions on empty state, then the click analytics logic still applies causing javascript errors.

I think we should have an extra condition here that check that the suggestion has __queryID defined
https://github.com/algolia/algoliasearch-magento/blob/master/js/algoliasearch/click_conversion_analytics.js#L16

**Comment by damcou** [comment]
Hello there, I'm closing the issue as we didn't hear from you for a while.

Regarding the issue raised previously, the related PR is still existing and will be addressed as soon as possible.

In the meantime, you can keep track of it looking at our [M1 community board](https://github.com/algolia/algoliasearch-magento/projects/3).

If you are still experiencing further issues, please reach out to us at support@algolia.com with any error logs, screenshots of examples you can provide, as well as your APPID so that we can further assist you. Thanks!
