### ISSUE TITLE
algolia_queue_runner is not releasing reindex_full lock

### ISSUE THREAD

**Issue by PascalBrouwers** [algolia/algoliasearch-magento#1160]
**Do you want to request a *feature* or report a *bug*?**

**Bug: What is the current behavior?**
`shell/indexer.php --reindex algolia_queue_runner` always setting the reindex_full.lock but never removing it

**Bug: What is the expected behavior?**
algolia_queue_runner index should release the full reindex lock

**Bug: What is the proposed solution?**
algolia_queue_runner index should release the full reindex lock

**What is the version of Magento and of Algolia extension you are using? Always use the latest version of the extension one before opening a bug issue.**
Magento 1.14.2.4

**Comment by bsuravech** [comment]
Hi @PascalBrouwers,

Can you confirm that the `algolia_queue_runner` has completed indexing successfully? Can you send us over the output after running the command? 

Are there any errors generated in the logs?

**Comment by damcou** [comment]
Hello there, I'm closing the issue as we are reorganizing our support process to make it more centralized.

Regarding the issue raised previously, be reassured, it has been added to our backlog and will be addressed as soon as possible, and fixed if applicable.

In the meantime, you can keep track of it looking at our [M1 community board](https://github.com/algolia/algoliasearch-magento/projects/3).

If you are still experiencing further issues, please reach out to us at support@algolia.com with any error logs, screenshots of examples you can provide, as well as your APPID so that we can further assist you. Thanks!

**Comment by PascalBrouwers** [comment]
I just manually delete the reindex_full.lock after algolia_queue_runner has ran. Not the best solution, but it's working now.
