### ISSUE TITLE
String in header

### ISSUE THREAD

**Issue by joybuggy** [algolia/algoliasearch-magento#1165]
Somehow we are getting " string(9) "0,00 DKK " string(5) "0,00 " " shown in our header.
If we disable Algolia this is gone again.
https://prnt.sc/svvb9g

How to fix this ? 

We are running on a Algolia 1.17.1 with a Magento 1.9.24

**Comment by bsuravech** [comment]
Hi @joybuggy,

Thanks for reaching out to us. Can you please elaborate on this issue by providing us with an example link? Additionally, let us know if there were any customisations or debugging in the extension that you or your team has done. You can send us further information through [support@algolia.com](mailto:support@algolia.com) so we can better address your issues there. We are closing this issue here and hope to see your ticket through support.
