### ISSUE TITLE
[Question] Is partial update possible

### ISSUE THREAD

**Issue by maxiloc** [algolia/algoliasearch-magento#136]
@aphroz

**Comment by maxiloc** [comment]
This could allow to be able to index some attribute via other sources than magento

**Comment by redox** [comment]
As soon as the other source knows the `objectID` of the target product, I don't see any issue with that.

But if it's for "optimization" (avoid sending the whole product, just the modified attributes) it's not worth it because it costs approximatively the same.

**Comment by aphroz** [comment]
Actually the problem is that we use multiple source to enrich the Algolia index. When Magento send the information to Algolia, all the existing data is wiped.

I use the function "partialUpdateObject" to enrich the existing data without losing the existing data, but I lose this information when the product is updated again from Magento.

**Comment by redox** [comment]
Ah yes indeed @aphroz, good point. So if we used `partialUpdateObject` instead of `addObject` in the Magento extension itself, would that fix the issue? Or should you build another index based on the one the extension is creating + your external data -> maybe it's simpler (because the data will always been consistent).

**Comment by aphroz** [comment]
I believe it will fix the issue indeed. If I create another index it will multiply the records but I don't really see the improvement. A good thing would be the possibility to chose the behaviour in the backend of Magento.

**Comment by redox** [comment]
Yeah my only concern is that if we use `partialUpdateObject` in the extension you'll never really manage to tell your external source to update the new products just after the extension created them. Having another index would allow you to do like:

Every X minutes run:
```
for each record in ORIGINAL_INDEX:
  fetch extra data from EXTERNAL_SOURCE
  push enriched object to NEW_INDEX
```

SO NEW_INDEX will always be consistent (every products will always have all attributes). Use NEW_INDEX in the JS code.

**Comment by aphroz** [comment]
In my case all the products will be updated every day and the data is pushed to Magento and to Algolia from an ETL that manages both.

**Comment by maxiloc** [comment]
@aphroz It's implemented. Will be available with next release

**Comment by aphroz** [comment]
Thanks!

**Comment by manuelgodoy** [comment]
Is this available? It is not working for me.

**Comment by maxiloc** [comment]
@manuelgodoy Yes it is. Did you enable it ?

**Comment by manuelgodoy** [comment]
What do you mean by enabling it? I am using algolia's python library which seems to be making the right call to the server.

**Comment by maxiloc** [comment]
I mean Magento extension by default use addObjects if you want the extension to do partialUpdates you need to enable that in the advanced options

**Comment by aphroz** [comment]
Is this option working, because I enabled it and the indexation is still discarding the existing data in the index.
