### ISSUE TITLE
algolia search replaces theme catalogue page and pagination is not working.

### ISSUE THREAD

**Issue by MrYogi** [algolia/algoliasearch-magento#173]
Algolia injects a new search result markup into catalog page and you need to specify the right "DOM Selector" in config settings (System > Configuration > Algolia Search > Instant Search Results Page Configuration)

The default DOM Selector is ".main" but this is for the default rwd theme. I have changed the selector to ".products-grid" and now the extension is able to overwrite the catalog page. However, since the extension injects a different markup the CSS of the theme for the grid is ignored and pagination is not working on catalogue page. 

i want catalogue page as per my theme, please help
if needed i can give website details etc.

**Comment by maxiloc** [comment]
Indeed we replace the markup by a js generated html to have a very fast rendering. You can modify it to have the same look. If your pagination do not work it is probably because you did not choose the right div. We create our own pagination so your DOM Selector need to include the pagination.

If you do not want to touch anything you can disable instant search. You will loose speed as the query will be performed in the backend but you will have your magento template
