### ISSUE TITLE
Display refined filters + ability to clear them all

### ISSUE THREAD

**Issue by aphroz** [algolia/algoliasearch-magento#181]
Would it be possible to display the search filters as in Jadopado (toggle, clear filter, delete filter one by one):

![image](https://cloud.githubusercontent.com/assets/261406/9462471/69597d2c-4b16-11e5-8830-d6cab438c6c4.png)

Thank you

**Comment by redox** [comment]
Displaying the selected filters is definitely on our roadmap but we're waiting for the release of our [instantsearch.js](https://github.com/algolia/instantsearch.js) library to be able to implement it more easily/generically.

Regarding the facets collapsing, it seems that it's more part of the store theme rather than a default behavior of the extension. I would recommend to add custom JS/CSS code for that.

**Comment by maxiloc** [comment]
This has been implemented and will be part of next release
