### ISSUE TITLE
Can you elaborate on 1.4.5 fix

### ISSUE THREAD

**Issue by WesMage** [algolia/algoliasearch-magento#204]
Hi @maxiloc 
Can you elaborate on what this change means please
"FIX: Improved performance of backend-search queries (used for SEO)"
Thanks in advance
(ps. Sorry if an "issue" is not the correct way to ask this question. I am new to github.

**Comment by maxiloc** [comment]
@WesMage Yes sure.
Before the fix here https://github.com/algolia/algoliasearch-magento/blob/master/code/Helper/Data.php#L74
we were fetching 1000 results no matter what and let magento handle it. Some customers had a slow loading of the search page because of that.
In case instant search is enabled we do not need pagination and facet count to work because we only want the first results for seo. So we reduced it to the number of results (9 by default) if instant search is enabled.
Does that make sense ?
