### ISSUE TITLE
When upgrading, all template/JS customization is gone

### ISSUE THREAD

**Issue by vvo** [algolia/algoliasearch-magento#220]
When a client has done some template/JS customization in Algolia magento search, when he upgrades, all the modifications are gone.

Could we find a way where we advise people to maybe do the customization in another file? I wonder what's feasible

**Comment by redox** [comment]
I would create a new "Templates" section in the administration console and I would expose all templates there through `textarea`. I don't think it's sustainable to keep templates in the files we're updating on each releases. Probably the same for CSS.

**Comment by redox** [comment]
@maxiloc what do you think?

**Comment by maxiloc** [comment]
@redox I am not convinced by the textarea in the admin for html elements.

Two main reasons:

- We are gonna have issue when people update the plugin if we want to make some changes. We won't be able to erase settings they currently have which for me is not good => hacky way to update

- Related but a bit different, I am afraid of people who will break the autocomplete or instant search because they put some bad thing in those textareas. Right now they could just uninstall/reinstall, and you have everything working again. If you put templates in textarea that won't be an option => more support

For me explaining how to do an override correctly seems to be a better way.

For comparison: Other similar extensions only allow to modify css

What do you think ?

**Comment by redox** [comment]
> We are gonna have issue when people update the plugin if we want to make some changes. We won't be able to erase settings they currently have which for me is not good => hacky way to update

For me that's an issue of our plugin. It was OK for now, but we cannot ask the user to "loose" everything after each upgrade. If it's a minor upgrade we need to keep the backward compatibility and if it's a major upgrade we need to provide a migration guide.

> Related but a bit different, I am afraid of people who will break the autocomplete or instant search because they put some bad thing in those textareas. Right now they could just uninstall/reinstall, and you have everything working again. If you put templates in textarea that won't be an option => more support

Yes, I think for that we need to have a way to reset the configuration; is the configuration not removed after uninstalling the plugin?

> For comparison: Other similar extensions only allow to modify css

Modifying the CSS in such textarea is a must have as well. Regarding the HTML, I'm afraid we cannot do without it because we want our user to customize it as they want -> it's one of our strength.

**Comment by redox** [comment]
Still, I'm mostly speaking about the hit (and maybe the refinement list) template(s), the others are not required.

**Comment by vvo** [comment]
> Yes, I think for that we need to have a way to reset the configuration; is the configuration not removed after uninstalling the plugin?

Yes a "reset" configuration should be feasible.

As for customizing. We can propose our users to add a custom JavaScript file if they need it and propose them an API to override some configuration/templates:

```js
algoliaInstantSearch.templates = {
  hits: {hit: ..}
}
```

This way the customization API of the extension is well defined, it's all in algoliaInstantSearch.

Then from your implementation, you can just check if (algoliaInstantSearch..) then you have customization.

Then the user is responsible for inserting the JS file in his templates. What do you think?

**Comment by maxiloc** [comment]
> Yes a "reset" configuration should be feasible.

Seeing how Magento handle configuration I am not sure about about that.

> As for customizing. We can propose our users to add a custom JavaScript file if they need it and 
propose them an API to override some configuration/templates

Yes that would be feasible but for me in should be in a php file and not a js file, people wanting to access Magento config need to be able to do so.

>Yes, I think for that we need to have a way to reset the configuration; is the configuration not removed after uninstalling the plugin?

No, Magento does not do it and there is no hook to do that.

----
First of all: I agree with the benefit of templates in the configuration, but I think it might bring a lot issues/supports
Several points:
- I think if we go for that we can not go halfway. It seems weird to have only some template that you can modify, and even with that probably a lot of modifications would require to modify the js code. Then when updating it will result in the same issue we have right now.
- One point I just thought about is. We would also loose automatic translation by putting in the configuration

Again for me the best way to do it is to create an override of the topsearch.phtml, that way when implementing for the first time is just a copy paste of the original file and when we update the copy won't be touched. Then if it broke something there is still a way to fallback to the new version. And with a migration guide you can modify your old version to make it compatible.

**Comment by vvo** [comment]
> people wanting to access Magento config need to be able to do so

Once your implementation start looking for a JavaScript object called `algoliaInstantSearchCustomization` then the users can do anything they want, no need to force them using PHP or JS.

They just need to have this JS variable inside the scope before instantsearch.js init takes place. So it's only about their knowledge of magento.

**Comment by maxiloc** [comment]
I mean their own php configuration not the one we want them to have

**Comment by redox** [comment]
> I think if we go for that we can not go halfway. It seems weird to have only some template that you can modify, and even with that probably a lot of modifications would require to modify the js code. Then when updating it will result in the same issue we have right now.
> One point I just thought about is. We would also loose automatic translation by putting in the configuration

For me only the hits and the CSS make sense, those are the two things our users update all the time. The good thing is that we "probably" don't need translation there. I don't think it's an issue to only expose those ones.

**Comment by maxiloc** [comment]
As discussed let's close this, topsearch.phtml file is way better now, we just need to document it for 1.5 release (https://github.com/algolia/algoliasearch-magento/issues/238)
