### ISSUE TITLE
Root category is displaying in search popup product list

### ISSUE THREAD

**Issue by manish172** [algolia/algoliasearch-magento#225]
category without path in product hit template shows the root level category. It should exclude the root level categories by adding the root level category filter ($categoryCollection->addRootLevelFilter())

**Comment by maxiloc** [comment]
@manish172 I am not able to reproduce your issue. If you look at https://magento.algolia.com which as the demo data of magento we don't have the root category.
I made some test and the only time it shows the root category is when products have the root category as one of the category. For me this is the expected behavior.

Can you give me more details how to reproduce it

**Comment by manish172** [comment]
@maxiloc Yes, You are correct. This is the scenario when product is also assigned to root category.

**Comment by maxiloc** [comment]
Yes so I will keep it like that, I think it's make sense like it is right now

**Comment by manish172** [comment]
@maxiloc I think this should be fixed because there are many customers who associate the products to root categories for some reason (like promotions etc.) and display root category in search pop is irrelevant in any scenario.

**Comment by maxiloc** [comment]
@manish172 addRootLevelFilter actually filter the collection to have only root categories :smile:.
