### ISSUE TITLE
addFinalPrice is using the price index which is not reliable

### ISSUE THREAD

**Issue by maxiloc** [algolia/algoliasearch-magento#297]
Steps to reproduce:
- Enable the queue
- Update a product, reindex
- go into the price index and delete references to that updated product
- add that product to the algolia queue and attempt to process the queue

Possible way to fix it:
- change the value of use_price_index thanks to catalog_product_collection_apply_limitations_before

**Comment by chrisvanderpoel** [comment]
The problem revolves around the query generated by `Algoliasearch/Helper/Entity/Producthelper::getProductCollection`.  This method leverages the `addFinalPrice` method for adding pricing information to the collection.  This `addFinalPrice` method is actually an alias for `Mage_Catalog_Model_Resource_Product_Collection::addPriceData` which, in turn, immediately sets itself up to use the price indexes:

`$this->_productLimitationFilters['use_price_index'] = true;`.

Where this can be problematic is when products are introduced into the system and the price indexes have not been (or had a chance to) run.  This results in a collection query that will return 0 products (due to the way the join is structured) and a program flow that will not understand that this is an issue and simply mark the queue batch as done and remove it.

In the end, this manifests itself with products being in the Magento catalog that do not exist in Algolia with the only way to sync things being a full reindexing of the Algolia indexes (obviously, not ideal with large catalogs).

**Comment by maxiloc** [comment]
@chrisvanderpoel Can you try this fix https://github.com/algolia/algoliasearch-magento/commit/f6542e2b93f6a6776d9840df39365403d640f555 ?

**Comment by maxiloc** [comment]
Let's close this and re-open if needed

**Comment by michaelwylde** [comment]
@maxiloc I tried your patch and it does add the item to Algolia, however it does not add any pricing information. This causes Magento and Algolia to become out of sync, albeit less out of sync then the original request, therefore I think this issue should be re-opened.

**Comment by maxiloc** [comment]
@michaelwylde We did not receive any complain about this for a while. Are you experiencing an issue with the price index ?

**Comment by michaelwylde** [comment]
@maxiloc I think this is because in Magento Enterprise the price index is updated in the background and is therefore not present when the product is created.

**Comment by JanPetr** [comment]
@michaelwylde I see, are you experiencing the issue in the end?

**Comment by michaelwylde** [comment]
@JanPetr Yes I am currently experiencing this issue when adding new products. I have to either wait for the price_index to be populated or force run it, then edit the product again for it to be added correctly.

**Comment by chrisvanderpoel** [comment]
Yes, this is going to be specific to Enterprise.  The Enterprise cron indexers run every minute on the minute.  The setup instructions tell you to use the algolia queue runner to process the queue, this also will be executed on the minute in a different process.  This can lead to some race conditions that you see being manifested here.

The least complicated way to handle it is to try and treat the running of the Algolia queue similarly to that of the Materialized View Indexes: Synchronously.  Without rewriting the entire extension, the best way to get around the issue is to remove the algolia queue runner cron process and overload the enterprise indexer refreshIndex method.  Simply have it dispatch an event when complete which you can then listen for to process the Algolia queue.

One caveat to this approach is that the enterprise_refresh_index will take a bit longer to run if you have a bunch of stuff in the queue.

**Comment by michaelwylde** [comment]
This issue is not just related to the price index but I have experienced it with the cataloginventory_stock index.

One way to deal with this situation is to before processing the event, check the _cl tables for all product_id's that are in a "pending" state (ie. where version_id > enterprise_mview_metadata.version_id). If the product we are going to send to Algolia is in this list then we simply do not process the event this time. When the reindex occurs the product will no longer be in "pending" state and the Algolia process will run successfully the next time.

**Comment by JanPetr** [comment]
Thanks for the hint @michaelwylde,
I'm reopening the issue and will investigate. When I'll have something I'll come back to you.

**Comment by michaelwylde** [comment]
No worries @JanPetr.
I have implemented my idea here: https://github.com/aligent/AlgoliaEEIndexing Hopefully it helps with your investigations.

**Comment by redox** [comment]
> I have implemented my idea here: https://github.com/aligent/AlgoliaEEIndexing Hopefully it helps with your investigations.

Thank you for contributing that back to the community @michaelwylde 👍

**Comment by JanPetr** [comment]
Hello @michaelwylde,

thank you for your amazing work on that one. Your work is great!
If you don't mind, I reimplemented your code directly to the Algolia extension so we can maintain it and keep it in sync with a future changes. The pull request is here: https://github.com/algolia/algoliasearch-magento/pull/726

I would really appreciate if you could find some time and review it. It would mean a lot to have your POV on it and I will be very happy for any feedback.

And can you send me you T-shirt size and address to honza@algolia.com?

Thanks again! Cheers.
