### ISSUE TITLE
Customer Group prices

### ISSUE THREAD

**Issue by Ilia** [algolia/algoliasearch-magento#319]
Hi,

Is there anyway that we can get the customer group price without all prices being sent back from algolia service? It seems odd that users can see this without even logging in.

ie 
![screen shot 2016-02-18 at 1 36 20 pm](https://cloud.githubusercontent.com/assets/75891/13132166/ae40d44e-d644-11e5-9728-b75db4172044.png)

**Comment by Ilia** [comment]
Any help is greatly appreciated on this

**Comment by aude** [comment]
Users have access to everything that is allowed by the search API key. As far as I can see, that means that the only way to properly restrict it is to create a separate API key for each customer group.

**Comment by maxiloc** [comment]
No right now this is not possible. We have a feature that is not yet implemented in the engine that would allow to do this in the coming weeks. Let keep this open in the meantime

**Comment by Ilia** [comment]
Thank you

**Comment by maxiloc** [comment]
Done it will be available with next release

**Comment by lazyguru** [comment]
@maxiloc e666370 seems to deal with retrieving the data securely, I don't see a commit where the data is stored securely (or access is restricted).  What is to stop someone from using the search API key to query the data?  Or is that a function in the dashboard and not in Magento?

**Comment by maxiloc** [comment]
With this the search api key becomes private. It should not appear on the frontend.
Each time we render the search we generate a "secured" key, that is only allowed to retrieve relevant attributes for the current customer group.

Does that makes sense ?

**Comment by lazyguru** [comment]
You are still outputting the key to the page for use by JavaScript.  I don't see anything added to the indexing logic to restrict access to specific fields by a specific API key.  So I could still scrape the API key from the page and make a request to the API retrieving all fields.

**Comment by maxiloc** [comment]
No it's not the same key. The key appearing in the frontend is generated at query time with the restriction included in the key. The search key you enter in the credentials will never appear on the frontend.

Your right their is nothing in the indexing logic, this is because generating a secured keys does not require a call to algolia.

Here is relevant parts of the code regarding this:
In magento:
- https://github.com/algolia/algoliasearch-magento/blob/e6663708b79ba49c74782c93125171cf1bffa0b3/code/Helper/Algoliahelper.php#L34
- https://github.com/algolia/algoliasearch-magento/blob/e6663708b79ba49c74782c93125171cf1bffa0b3/design/frontend/template/beforetopsearch.phtml#L111

In the api client
-https://github.com/algolia/algoliasearch-client-php/blob/master/src/AlgoliaSearch/Client.php#L642-L687

**Comment by lazyguru** [comment]
ok, I see it now.  Thanks for the clarification

**Comment by aude** [comment]
Creds @maxiloc and Algolia for smooth solution B)
