### ISSUE TITLE
Use Include in Navigation Menu to say if we index a category or not

### ISSUE THREAD

**Issue by rbrown** [algolia/algoliasearch-magento#321]
Was d7c01b74a1277eeabf0676d7a26fe39814ec113d the result of a user request or anything? Is there any chance of having it reverted or as a config flag? We use the option at the moment to differentiate between categories that appear on the top menu and ones that can only be reached by browsing through the hierarchy

**Comment by maxiloc** [comment]
Yes we can definitely add an option

**Comment by technik-vitafy** [comment]
We also need the indexing to be decoupled from the category option "include_in_menu" since some categories must not appear in the navigation but still must be available for other purposes (e.g. special deal/sale categories for marketing purposes).

**Comment by lazyguru** [comment]
I don't think that #312 is working as intended?  We use "include_in_menu = no" for promotional landing pages that are category driven.  The way this was implemented it seems to remove the category from the index completely. Since Algolia is used to drive category navigation, the only way this category will display products is if it is in the index.  What we need is for this category to not be included in search results or search filters, but it should still be indexed so that it can display products when viewed

**Comment by maxiloc** [comment]
@lazyguru We can go for two options. 1 for display, 1 for index, would that work for you ?

**Comment by lazyguru** [comment]
Yes, I think

**Comment by lazyguru** [comment]
It should work similar to the visibility filter for products.  Add a attribute to the index for categories for the include_in_menu value and then use it for returning search results (if config is set)
