### ISSUE TITLE
Apply new magento2 update strategy

### ISSUE THREAD

**Issue by maxiloc** [algolia/algoliasearch-magento#337]
When a product is saved:
- delete
- push

**Comment by sammarcus** [comment]
Hi, just wanted to pop in and see if there was an approximate timeline for full (or even partial bare minimum) compatibility with Magento 2.0? I'm not clear on the architectural differences between the versions so am not sure how much work is needed to adapt the extension to bring it up to compatibility. We had to unexpectedly move our timeline forward due to other dependencies and have already begun testing 2.0 for this reason. Thank you for the info!

**Comment by maxiloc** [comment]
@sammarcus We have a working alpha magento2 module => https://github.com/algolia/algoliasearch-magento-2
You can test it as much as you want, submit issues and PR but we won't provide support on it until v1

**Comment by sammarcus** [comment]
@maxiloc Wow, tremendous, thank you! Something like a _Known Issues_ section would be really helpful if at all possible :)

**Comment by maxiloc** [comment]
@sammarcus Not really it's really new, we shared it with a few people waiting for feedback, you should see issue(s) popping in the new repo very soon

**Comment by sammarcus** [comment]
Oh, ok, sounds good. Thanks again!
