### ISSUE TITLE
Unexpected rendering

### ISSUE THREAD

**Issue by thoaionline** [algolia/algoliasearch-magento#349]
Our site https://www.schots.com.au/ is using this plugin for product search.

On a sub page, the search works fine

https://www.schots.com.au/furniture.html

![screen shot 2016-04-07 at 4 23 56 pm](https://cloud.githubusercontent.com/assets/229556/14342470/292c4170-fcdd-11e5-9ed5-96fb4a55f090.png)

However, on the homepage (only), the panel always overflows:

![screen shot 2016-04-07 at 4 23 20 pm](https://cloud.githubusercontent.com/assets/229556/14342458/1a5ddc94-fcdd-11e5-83be-6192f1972c33.png)

Can you sed some light on [A] how the search panel is constructed and rendered and [B] whether there's a CMS option to customise this?

**Comment by maxiloc** [comment]
To be able to have a large autocomplete in every website, we are forced to hook the dropdown in the “content" block instead of "top.search". Because of this if we do nothing the dropdown is not aligned with the input. So we have a function that make the dropdown stick to the input and is able (most of the time) to decide whether to stick on the left or on the right => 
https://github.com/algolia/algoliasearch-magento/blob/master/design/frontend/template/beforetopsearch.phtml#L455-L476
In your case the computation doesn't work properly because $(document).width() is returning unexpexted  large value. to fix it you can just replace "document" per "window" in this line https://github.com/algolia/algoliasearch-magento/blob/master/design/frontend/template/beforetopsearch.phtml#L455, that should do the trick

**Comment by thoaionline** [comment]
This is working well on our staging environment. Thanks @maxiloc!
