### ISSUE TITLE
Include data from out-of-stock sub products

### ISSUE THREAD

**Issue by thoaionline** [algolia/algoliasearch-magento#358]
Reference:

Algolia/Algoliasearch/Helper/Entity/Producthelper.php

In `Algolia_Algoliasearch_Helper_Entity_Producthelper::getObject()`, sub products that are out of stock are ignored.

```
                            if ($isInStock == false)
                                continue;
```

Is it possible to include an option to include these products in the index? Some stores (incl. ours) may want to show product information for pre-ordering. Note that Magento support pre-ordering for out-of-stock items if specified and this setting should be honoured.

**Comment by maxiloc** [comment]
This one is a bit tricky, we would probably go for an option since it not something all users want.

Regarding out of stock product, they are indexed if this magento config is set to true => https://github.com/algolia/algoliasearch-magento/blob/master/code/Helper/Config.php#L58
https://github.com/algolia/algoliasearch-magento/blob/master/code/Helper/Entity/Producthelper.php#L82-L83

**Comment by thoaionline** [comment]
Shouldn't the same cms option be used to control whether sub product should show regardless of stock status?

**Comment by maxiloc** [comment]
I think it's not exactly the same. one is for whether to display or not a product, it make sense to use the magento method. The other is whether to index in the configurable product out-of-stock attributes.
Plus, this would be a BC so will need an option anyway
