### ISSUE TITLE
Magento 1.5 Compatibility

### ISSUE THREAD

**Issue by geoffjukes** [algolia/algoliasearch-magento#445]
Hi,

We are looking to replace our current search with Algolia, but we are running Magento 1.5

Is this extension compatible with 1.5? If not, do you know what piece(s) are not compatible? or if it is even possible to make it 1.5 compatible?

We have 3 sites running 1.5, which are being upgraded to 1.9 this year. But we need to switch our search before that process is complete.

Any feedback gratefully received,

Geoff

**Comment by maxiloc** [comment]
@geoffjukes The biggest issue is the indexer system that have been added in 1.6, it would be a pain to write because the extension heavily relies on it. I am not sure it worth trying to make it work.

If you want to use algolia with 1.5, I would go for a classic implem (without any extension) using our php client, and make a frontend implementation autocomplete/instantsearch using autocomplete.js/instantsearch.js.
