### ISSUE TITLE
category Facet:: Disjunctive not working

### ISSUE THREAD

**Issue by talha-malik** [algolia/algoliasearch-magento#513]
Hi,
I want to show categories as checkboxes. As per docs I should select disjunctive property to make facet appear like checkboxes. From Admin panel under Instant search results tab I have options to add facets and select facet type. I selected disjunctive for Categories but no effect. Also made colors facet conjunctive it did not had any effect too. Please guide. Using version 1.5.5.

Thanks

**Comment by JanPetr** [comment]
Hello @talha-malik,
sorry for the late answer. Categories has their own custom widget (hierearchical menu). If you want to change, please navigate here: https://github.com/algolia/algoliasearch-magento/blob/master/design/frontend/template/instantsearch.phtml#L265-L296 Here you can find the custom widget. If you just want `categories` to behave like standart refinements lists, you should just delete these lines. It should do the trick.

I tested `colors` facet and it works as expected. What do you exactly mean by "not having any effect"?

**Comment by JanPetr** [comment]
Hey @talha-malik,
do you have any updates on the issue? Did you manage to make it work?

**Comment by talha-malik** [comment]
Hi, 
@JanPetr I am sorry I have been away. I have not tried above yet. I am closing this for the time as I will not be able to work on it for some days. Will reopen if required.
Thanks

**Comment by Inwerpsel** [comment]
Hi,

Commenting out the lines (which are now at [)](https://github.com/algolia/algoliasearch-magento/blob/master/js/algoliasearch/instantsearch.js#278-305) is no solution: it doesn't work because category facets are only in search results with keys for each level. The is no "attributes" facet in the results, only "attributes.level0", "attributes.level1", ... Even if you rewrite the code to make it work it would still only be able to display one specific level because the regular refinementList widget doesn't support hierarchy.

Would really like to see this as a feature though.
