### ISSUE TITLE
Index operation with algolia 1.6

### ISSUE THREAD

**Issue by bastienlm** [algolia/algoliasearch-magento#520]
Hello,

I'v just update algolia 1.5 to 1.6.1 and when i reindex algolia search index, algolia make 65,816 opération and re-index during 4m31. When i switch to the version 1.5 I'v just 3,326 opération and 53s when i reindex algolia search.

Do you know why ?
Thank you.
Regards,
Bastien

**Comment by JanPetr** [comment]
Hello @bastienlm,
do you have indexing queue enabled?

If you don't there have been a change when during the re-indexing without indexing queue the extension walks through ALL Magento products and checks if each of the products is indexable (is enabled, is visible, is on stock, ...). If the product doesn't meet indexing requirements the extension sends Delete command to Algolia so the product does not appear in search results. If the product meets the requirements, it's indexed.

In the same case in 1.5.x versions the extension fetched only available products and indexed them. That had an issue that old products were not deleted from Algolia and were still available in search.

That's why you had lower operation count and indexing time in the version before. But there was a possiblity you will have non-available products in index.

The best way to solve it is to enable indexing queue. With enabled indexing queue the extension fetches only available products, indexes them into temporary index and then move temporary index to production. So it will generate the same amount of operations. You can find more information about that here: https://community.algolia.com/magento/documentation/#full-products-reindex

**Comment by bastienlm** [comment]
Alright, I go enabled the indexing queue, thank you !
