### ISSUE TITLE
Lost compatibility with PHP 5.3

### ISSUE THREAD

**Issue by sam327** [algolia/algoliasearch-magento#527]
I'm in the process of upgrading algolia (from 1.5.5), and when I do the update in my dev site, I get this error.

Parse error: syntax error, unexpected '[' in /var/www/vhosts/mysite.com/root_folder/app/code/community/Algolia/Algoliasearch/Helper/Config.php on line 68 

which is a line that says ``` protected $_productTypeMap = [];```

Looking this up, it looks like this short array syntax - Using [] instead of array() - was introduced in PHP 5.4.

And that breaks horrifically on my php-5.3 system.

1) Outside of the syntax on the array, are there other major changes that require 5.4? I.e. am I in for a world of hurt if I try to force this back to 5.3?

2) If dropping 5.3 support is intentional, that's fine by me. But can I ask you to insert changes to the system requirements in the change log file?

That would make it a lot easier to budget (time and money) for upgrades like this.

**Comment by JanPetr** [comment]
Hello @sam327,
the change was intentional as Magento officially supports only PHP 5.4 or higher now.
But we got couple requests on restoring of PHP 5.3 support. So we did! Here is PR restoring the support - #523.
In next days we will release 1.7.0-RC version. So if you'll wait few days you'll be able to update directly to newest version 🎱

**Comment by JanPetr** [comment]
Even though the extension will support PHP 5.3, I'd definitelly recommend you to update your PHP version. To at least 5.6 as this one is still supported and have updates and security fixes - http://php.net/supported-versions.php
