### ISSUE TITLE
Nothing is stopping Magento from performing the search query (or fetching category products)

### ISSUE THREAD

**Issue by Inwerpsel** [algolia/algoliasearch-magento#714]
Thereby unnecessarily increasing server response time.

Magento's search results are hidden at the frontend by following code:
```javascript
        document.write(\'<style type="text/css"> ' . $config->getInstantSelector() . '{display:none}</style>\');

**Comment by Inwerpsel** [comment]
Hello @JanPetr,

I think the comment saying "Hide the instant-search selector ASAP to remove flickering. Will be re-displayed later with JS." is misleading: although it isn't false, in that the next line indeed also prevents flickering, it should really tell the whole story so developers know what is happening and can take action.

It would be helpful to add something like: "Hide the search results rendered by the server, which are also executed because we are not sure whether Google indexes the results that are fetched through JS." Even better would be to add this as a comment to the configuration setting for the instant selector, where most people implementing this module will see it.


As for SEO, couldn't this actually have an adverse effect? Google might consider instantly changing the entire content of a page with JS as cloaking and thus penalize the website. Escpecially when it is implemented in way that really looks like you are actually trying to trick Google.

Google can in fact interpret JS when indexing, as stated in [this FAQ from Algolia](https://www.algolia.com/doc/faq/why/the-impact-of-algolia-on-seo/). In some of the articles that are mentioned server side rendering is encouraged as the safest solution, but that would be server side rendering of the same JS as is used on the frontend and should return the same page.
If you let both Magento and algoliasearch's JS render the same url these will return two pretty different pages.


If by having a negative impact on accessibility you mean that people visiting the site with JS disabled won't see the search results, a default Magento installation will not work properly with JS disabled anyway. You would really have to tweak a theme to have Magento work with JS disabled as is described well in [this Magento Stackexchange post](http://magento.stackexchange.com/questions/11041/usage-of-javascript).

**Comment by JanPetr** [comment]
Hello @Inwerpsel,

thanks for your research.
The message you're mentioning in the first paragraph is also true and you're right that it can be added as a comment to the code. I'll add it.

From our research and our data we got confirmed that Google indexes the data rendered by server side and so far we didn't notice any harmful impact on SEO with changing the site with JS. Maybe it's because the page is very similar to the server-side rendered one and therefore Google doesn't consider is as cloaking.

Having the very same page rendered on the server would mean to bring additional complexity to the extension right now. But you're right that it would be better and eventually it might appear on our roadmap for the extension.

Thanks for your feedback!
