### ISSUE TITLE
Magento 1931 + Algolia 1.8

### ISSUE THREAD

**Issue by tomekjordan** [algolia/algoliasearch-magento#740]
Hi. Can somebody tell me what's going on. I'm getting Please Provide an API key msg in console. after update from Magento 1924 to 1931 and from Algolia 162 to 180. Really strange. since I have all API keys filled. Or it is a problem of multiwebsite env? or because my store load it via CNAME subdomain? All searching features works. only this is seen in the console

```
message
:
"Please provide an API key. Usage: algoliasearch(applicationID, apiKey, opts)"
name
:
"AlgoliaSearchError"
stack
:
"Error↵    at a.r (https://cdn2.site.pl/js/algoliasearch/internals/frontend/algoliaBundle.min.js:6:8647)↵    at a.r (https://cdn2.site.pl/js/algoliasearch/internals/frontend/algoliaBundle.min.js:25:3750)↵    at new a (https://cdn2.site.pl/js/algoliasearch/internals/frontend/algoliaBundle.min.js:6:30002)↵    at Object.o [as algoliasearch] (https://cdn2.site.pl/js/algoliasearch/internals/frontend/algoliaBundle.min.js:6:29974)↵    at HTMLDocument.<anonymous> (https://site.pl/bebiko-2-z-nutriflor-800-g.html:554:48)↵    at u (https://cdn2.site.pl/js/algoliasearch/internals/frontend/algoliaBundle.min.js:4:9792)↵    at Object.add [as done] (https://cdn2.site.pl/js/algoliasearch/internals/frontend/algoliaBundle.min.js:4:10094)↵    at ge.fn.init.ge.fn.ready (https://cdn2.site.pl/js/algoliasearch/internals/frontend/algoliaBundle.min.js:4:12180)↵    at ge.fn.init (https://cdn2.site.pl/js/algoliasearch/internals/frontend/algoliaBundle.min.js:4:7621)↵    at Object.ge [as $] (https://cdn2.site.pl/js/algoliasearch/internals/frontend/algoliaBundle.min.js:2:15298)"
__proto__
:
Error
```

**Comment by royduin** [comment]
Did you save the api key again from the backend after de update? The API key is stored encrypted in the latest version.

**Comment by tomekjordan** [comment]
Yes, I checked it today again. copying all 3 keys to Magento panel. and the same result. Searching works, but error appear in chrome console

**Comment by JanPetr** [comment]
Hello @tomekjordan, would you mind sharing a live website with me where I can check it? If you don't want to post it publicly, you can send it to support+magento@algolia.com.

Thanks!

**Comment by tomekjordan** [comment]
dzieckoimy DOT pl

**Comment by JanPetr** [comment]
Thanks @tomekjordan,
the issue is, that you have autocomplete loaded twice into the website. And one of those is legacy version. It looks like you didn't upgrade the extension properly.

One version (correct one) is loaded via JS file - https://cdn1 (dot) dzieckoimy (dot) pl/media/extendware/ewminify/files/js/08172eae12f184c6.js
The second version is loaded directly to the page: view-source:https://dzieckoimy (dot) pl/catalogsearch/result/?q=a - line 496.

In the second version you pass to `algoliaConfig.apiKey` as an API key, but it was changed and `algoliaConfig.autocomplete.apiKey` should be used now. The previous one doesn't exist anymore.

I'd suggest you to review how you upgraded the extension and delete all extra files which were removed from the latest version. Then you won't have an issues with twice-loaded JavaScripts.
