### ISSUE TITLE
Avoid duplications in queue

### ISSUE THREAD

**Issue by Mobecls** [algolia/algoliasearch-magento#745]
Is there a way we could avoid duplications in queue table at mysql? 

Right now product might be updated twice, and that means that it will be added to the queue twice... and indexed twice...

**Comment by JanPetr** [comment]
Hello @Mobecls,
when the queue is processed, duplicated jobs [are merged if possible](https://github.com/algolia/algoliasearch-magento/blob/master/app/code/community/Algolia/Algoliasearch/Model/Queue.php#L206). However sometimes it's not possible in order to keep the data 100% synchronised with Algolia. I wouldn't recommend to remove duplicates or not to insert duplicate jobs, because it could happen that your data won't be consistent between Magento and Algolia.

I believe you understand.
