### ISSUE TITLE
Unnecessary deletions

### ISSUE THREAD

**Issue by Mobecls** [algolia/algoliasearch-magento#752]
We have reviewed the logs, and it seems, that 50% of our operations - are Delete operations in Indexes. And huge amount of Deletions is coming from the products, that were never added to algolia. 

`2017-02-09T09:47:16+00:00 DEBUG (7): >>>>> BEGIN REMOVE FROM ALGOLIA
2017-02-09T09:47:20+00:00 DEBUG (7): Product IDs: 80107
2017-02-09T09:47:20+00:00 DEBUG (7): <<<<< END REMOVE FROM ALGOLIA (3.8532199859619sec)`

Major part of our catalog - are configurable products. And it means, that we have a lot of disabled simple products. 

The problem is that whenever we change those products, Algolia adds product to Reindex Queue, and as the visibility of the product is "not visible" Algolia is making Deletion process. 

And it turns out, that the products, that were never added to algolia index are spending our operations.

is this usual behaviour and can we, somehow not spend operations on not visible products, that are part of configurable products?

**Comment by JanPetr** [comment]
Hello @Mobecls, 

That's true that in some cases it's inefficient and to be honest, it's on purpose. But not because of price or higher plans, that's definitely not the reason!

The reason is that the extension tries to always keep the data in sync with Algolia. This delete/update operations make sure that the data which should(n't) be in Algolia are correctly removed or added. So there are delete operations which seems to be useless, but those make sure that the product is removed. The extension cannot know if the product is or is not present in Algolia, so it send delete operation "just in case" and make sure it's in sync.

There is a way how to optimize it at least for a full reindex - indexing queue. If you use indexing queue, the delete operations are not performed on full reindex as only active products are pushed to Algolia's temporary index and this index is, when the reindexing is done, move to production by deleting previous production index. So there is no delete operations needed.

All information about indexing are described in our documentation: https://community.algolia.com/magento/doc/m1/indexing/

**Comment by Mobecls** [comment]
Hi JanPetr, 

this is the problem. We have Queue enabled and we don't use full reindex. 
We have queue indexer for set to be reindexed each 2 minutes. All other algolia indexers are set to "updated on save". And we udpated magento indexers twice a day.

At your documentation you are saying:

> The extension indexes only products which are:
>
> Visible (catalog, search or both)
> Enabled
> Not deleted
> In-stock (if you only want to show “in-stock” products)

It means, that you are not supposed to index products, that are not visible. And all our simple products, that are part of configurables - are Not Visible Individually.

So it seems, that algorithm doesn't have any solution on how to verify, if the product should be Deleted from algolia or should not and that is why if the product is not visible, you send Delete update just to be sure. 

That might be ok for others, but we have 21 000 simple not visible products. Whereas they form just  3500 configurable and visible products. It means, that 5 of 6 operations are wasted...
