### ISSUE TITLE
Why do we need category index

### ISSUE THREAD

**Issue by Mobecls** [algolia/algoliasearch-magento#755]
Hello @JanPetr, 

could you, please, tell me, why do we need to reindex categories of the product on each product change via admin area (when a product is changed, it's categories are getting reindexed"? And why do we need categories at all? 

As I understand, facets are getting categories from product information (as all products have a list of categories it is included in). In the code there is a comment: "In case of wrong credentials or overquota or block account. To avoid checkout process to fail". 

But we don't really understand, why it is needed. We are looking on optimizing our operations, and it seems, that it would be good for us to disable it.

**Comment by JanPetr** [comment]
Hello @Mobecls,

the categories index is for autocomplete menu, where you can search even for categories.

The change of the operation when the product is saved is there because the product might not be active anymore (you could save it's visibility, delete, ...) so we need to reindex the category to make sure the category still contains products and should be searchable in autocomplete menu.

**Comment by Mobecls** [comment]
@JanPetr i see, thanks. 

So if we don't use categories in search autocomplete - we may comment it in the code?

**Comment by JanPetr** [comment]
Yes, you can comment it in a code.

Since a new version (1.8.0) it's possible to turn off categories from autocomplete by setting "0" to a number of categories in Algolia configuration in Magento. But the extension would still index categories. It'd be nice if you could send a pull request which fixes it.

**Comment by Mobecls** [comment]
Hello @JanPetr JanPetr, 

we have done our fix as a standalone extension and we won't be able to make a pull request, but we will write how did we do that and what exactly, so that it would be easier for you to implement.

**Comment by Mobecls** [comment]
We have redefined (rewrited) method getProductsRecords () in Algolia_Algoliasearch_Helper_Data class:
we added deleting (unset) of results from the array  (return array) products in the end of code. These products have been sent to the server and after that the product's data in the request have not changed.
