### ISSUE TITLE
Cron update worked only the first time

### ISSUE THREAD

**Issue by maxiloc** [algolia/algoliasearch-magento#87]

**Comment by maxiloc** [comment]
Unable to reproduce it so I am closing it for now.

Before 1.1.1 cron job wasn't running. But with latest version it should work

**Comment by anbuf** [comment]
Ok, I fixed it. I had to switch all my products visibility from "Catalog, Search" to "No visible individually" and put them back  to "Catalog, Search". On Magento perspective, the Catalog and Search was working well but for Algolia they were all no searchable. Since we have a script to automatically create product I suspect our script to be the reason of this mismatch. Thanks for your time.
