### ISSUE TITLE
search box not lining up with template

### ISSUE THREAD

**Issue by lisaclio** [algolia/algoliasearch-magento#873]
Hi guys, I'm not a whizz at html but know the basics etc so need a bit of help.
I've managed to configure and install the algolia search but I'm having an issue with the the search box not lining up with the search title and the magnifying glass as you can see in the link I have provided. If I could just be told which file to edit and to what to help it all line up then you have helped me out loads.
[https://ashtondisc.co.uk/](url)

**Comment by alexgran** [comment]
I had a similar issue, due to the fact that when you leave the selector configured to default, algolia will replace the template used to show the search box with their own one (which didn't fit our CSS as well). Setting it to the real ID used by our template made the algolia template (base/default/template/algoliasearch/autocomplete.phtml) unsued and css etc was fine.

**Comment by JanPetr** [comment]
Hello @lisaclio,
did it help to change the selector?

I'm closing the issue now, but feel free to re-open if you still experience the issue.
