### ISSUE TITLE
Upgrade algoliasearch to 1.11.1 cant find table

### ISSUE THREAD

**Issue by HRR1337** [algolia/algoliasearch-magento#918]
Hi there,

I have 2 issues regarding the upgrade from 1.11.0 to 1.11.1.

#1. Is it possible to disable the blue row on top of whole magento screens with the indexing status?

#2. I have updated the algolia search via github manual. Can you also provide a sql to create the missing table? .algoliasearch_queue_log

Thanks!

HRR

**Comment by HRR1337** [comment]
Number 2 is fixed:

Add in phpmyadmin this:

CREATE TABLE IF NOT EXISTS `algoliasearch_queue_log` (
  `id` INT(20) NOT NULL auto_increment,
  `started` DATETIME NOT NULL,
  `duration` INT(20) NOT NULL,
  `processed_jobs` INT NOT NULL,
  `with_empty_queue` INT(1) NOT NULL, 
  PRIMARY KEY `id` (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8 AUTO_INCREMENT=1;

After that the queue is running :-)

**Comment by JanPetr** [comment]
Hello @HRR1337,

for the first point - no, it's not possible to remove it now. It's on purpose everywhere so you know how many jobs you have in the queue and how long it'll take. For the next version we can add a configuration to turn it off, but currently it's there for everybody.

The second point - should be done automatically via [Magento migration](https://github.com/algolia/algoliasearch-magento/blob/master/app/code/community/Algolia/Algoliasearch/sql/algoliasearch_setup/mysql4-upgrade-1.7.1-1.11.1.php). I just tested it and it was migrated OK.

**Comment by dannydnz** [comment]
This is actually quite a serious issue for people who aren't aware of how Magento install scripts work.

Steps to reproduce.

1) Install a version of  Algolia_Algoliasearch less than 1.11.0  but greater than version 1.7.1. Refresh caches etc
2) Upgrade Algolia_Algoliasearch to version >= 1.11.0

Expected.
Algolia_Algoliasearch works seamlessly.

Actual:
PDOException is thrown when executing the Algolia_Algoliasearch queue index.
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento.algoliasearch_queue_log' doesn't exist in

This is due to the version number specified on the mysql4-upgrade setup file name.
It's currently mysql4-upgrade-1.7.1-1.11.1.php however this file wasn't added in the upgrade from version 1.7.1 to version 1.11.1. 
It was added in the upgrade from version 1.10.0 to 1.11.0.

Formant is mysql4-upgrade-<from_version_number>-<to_version_number>.php

In this case the file name should of been mysql4-upgrade-1.10.0-1.11.0.php

For anyone else experiencing this issue run this sql query in you DB (Make sure you backup first). Refresh all caches.
````sql
UPDATE core_resource SET version = "1.7.1" , data_version = "1.7.1" WHERE code LIKE "algoliasearch_setup";
````
This will trigger the upgrade script to execute.

**Comment by HRR1337** [comment]
Hi Jan Petr,

About the first issue with the big blue row... Please make a configuration to disable it. For a merchant it has no use at all, and it only distracts. And dont see any value to see the indexing status of algolia when you are working on cms pages etc..

Thanks,

HRR

**Comment by JanPetr** [comment]
Thanks for the thorough explanation @dannydnz. I'll fix it in the next version!

@HRR1337, it's already on my roadmap, thanks for bringing it up! 💯

**Comment by JanPetr** [comment]
@HRR1337 It's done in #920

**Comment by alexbogias** [comment]
Same issue here after upgrading from 1.10.0 to 1.11.0
